config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get '/recipes', to: 'recipes#index', as: 'recipes'
  post '/recipes', to: 'recipes#create'
  get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  get '/recipe/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  get '/recipe/:id', to: 'recipes#show', as: 'recipe'
  delete '/recipe/:id', to: 'recipes#destroy'
  patch '/recipe/:id', to: 'recipes#update'
  post '/recipe/:id', to: 'recipes#publish', as: 'publish_recipe'
  get '/recipes/search', to: 'recipes#search'

  get '/ingredients', to: 'ingredients#index', as: 'ingredients'
  get '/ingredients/list', to: 'ingredients#list', as: 'ingredients_list'
  get '/ingredients/show/:id', to: 'ingredients#show', as: 'ingredients_show'
  get '/ingredients/edit/:id', to: 'ingredients#edit', as: 'ingredients_edit'
  post '/ingredients/create', to: 'ingredients#create', as: 'ingredients_create'
  patch '/ingredients/update/:id', to: 'ingredients#update', as: 'ingredients_update'

  get '/profile/:id', to: 'profiles#show', as: 'profile'

  root 'welcome#index'

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  validates :name, presence: true, length: { minimum: 2 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :name, presence: true, length: { minimum: 2, maximum: 100 }
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :list]

  def index
    @ingredient = Ingredient.new()
    @ingredients = Ingredient.all.order(:name)
  end


  def list
    @ingredients = Ingredient.all
    return render(:json => @ingredients)
  end


  def show
    @ingredient = Ingredient.find(params[:id])
  end


  def edit
    @ingredient = Ingredient.find(params[:id])
  end


  def create
    s = IngredientService.new
    @ingredient = s.create(current_user.id, params[:name])

    if @ingredient.save()
      redirect_to(action: :index)
    else
      @ingredients = Ingredient.all
      render(:index)
    end
  end


  def update
    @ingredient = Ingredient.find(params[:id])

    begin
      s = IngredientService.new
      s.update(params[:id], current_user.id, params[:ingredient][:name])
      redirect_to ingredients_path()
    rescue Exception => e
      render(:edit)
    end
  end


  private


  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @recipes = Recipe.where(author_id: params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @recipes = Recipe.where.not(published_at: nil)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = Recipe.joins("LEFT JOIN recipe_ingredients ri on ri.recipe_id = recipes.id")
    .joins("inner join ingredients i on i.id = ri.ingredient_id")
    .select("ri.id, ri.amount, ri.importance, ri.ingredient_id, i.name")
    .where('recipes.id' => params[:id])
  end

  def new
    @recipe = Recipe.new()
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @ingredients = Recipe.joins("LEFT JOIN recipe_ingredients ri on ri.recipe_id = recipes.id")
      .joins("inner join ingredients i on i.id = ri.ingredient_id")
      .select("ri.id, ri.amount, ri.importance, ri.ingredient_id, i.name")
      .where('recipes.id' => params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    p = recipe_params

    success = @recipe.update(
      name: p[:name],
      text: p[:text],
    )
    success &&= helpers.update_recipe_ingredients(p[:ingredients])

    if success
      redirect_to(@recipe)
    else
      render(:edit)
    end
  end

  def create
    p = recipe_params

    @recipe = Recipe.new(
      name: p[:name],
      text: p[:text],
      author_id: current_user.id,
    )
    success = @recipe.save()
    success &&= helpers.update_recipe_ingredients(p[:ingredients])

    if success
      redirect_to(@recipe)
    else
      render(:new)
    end
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])

    if !@recipe.published_at.nil?
      @recipe.errors.add(:base, :recipe_published, message: "Cannot delete published recipe")
      render(:show) and return
    end

    @recipe.destroy
   
    redirect_to(recipes_path)
  end

  def search
    p = search_params
    ingredients = p[:ingredients].to_s.split(",").map{|o| o.to_i}
    render(:json => helpers.search(ingredients))
  end

  def publish
    @recipe = Recipe.find(params[:id])

    if @recipe.ingredients.blank?
      @recipe.errors.add(:base, :no_ingredients, message: "Cannot publish recipe with no ingredients")
      render(:show)
    else
      @recipe.update(published_at: Time.now())
      redirect_to(@recipe)
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :text, ingredients: [:ingredient_id, :amount, :importance])
  end

  def search_params
    params.permit(:name, :ingredients)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def update_recipe_ingredients(ingredients)
    return true if ingredients.nil?
    ingredients.each do |o|
      if o[:importance].to_i < 1 or o[:importance].to_i > 5
        o[:importance] = nil
      end
    end
    success = true
    success &&= RecipeIngredient.where(recipe_id: @recipe.id).where.not(ingredient_id: ingredients.map{|o| o[:id]}).destroy_all
    if !ingredients.empty?
      success &&= RecipeIngredient.where(recipe_id: @recipe.id).where(ingredient_id: ingredients.map{|o| o[:id]}).upsert_all(
        ingredients.map{|o| o.to_h.merge(
          recipe_id: @recipe.id,
          created_at: Time.now,
          updated_at: Time.now,
        )},
        unique_by: [:recipe_id, :ingredient_id]
      )
    end
    return success
  end

  def search(ingredients)
    q = <<-SQL
      select r.id, r.name
      from recipes r
      inner join (
        select ri.recipe_id as recipe_id, jsonb_agg(i.id) as ingredient_ids
        from recipe_ingredients ri
        inner join ingredients i
        on ri.ingredient_id = i.id
        group by ri.recipe_id
      ) ris
      on ris.recipe_id = r.id
      where ris.ingredient_ids @> jsonb_build_array(:ingredients)
    SQL
    Recipe.find_by_sql([q, :ingredients => ingredients])
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_login_links.html.erb
<div>
  <p>
    <%= link_to 'Front page', controller: '/welcome' %>
    <% if user_signed_in? %>
      <%= link_to 'Profile', profile_path(current_user) %>
      <%= link_to 'Log out', destroy_user_session_path(), method: "delete" %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path() %>
      <%= link_to 'Register', new_user_registration_path() %>
    <% end %>
  </p>
</div>

app/views/ingredients/_form.html.erb
<%= form_with model: @ingredient, url: :ingredients_create, local: true do |form| %>

  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ingredient.errors.count, "error") %>
      </h2>
      <ul>
        <% @ingredient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.submit %>
  </p>
<% end %>

app/views/ingredients/edit.html.erb
<%= form_with model: @ingredient, url: :ingredients_update, local: true do |form| %>

  <%=raw "#{t(:edit)}: #{@ingredient.name}" %>

  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ingredient.errors.count, "error") %>
      </h2>
      <ul>
        <% @ingredient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.submit %>
  </p>
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
 
<div>
  <h3>Submit a new ingredient</h3>
  <%= render 'form' %>
</div>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
 
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= link_to 'Edit', ingredients_edit_path(ingredient.id)  %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'core', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'common/login_links' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/show.html.erb
<p>
  Email: <%= @user.email %>
</p>

<h2>Submitted recipes</h2>
<%= render 'recipes/table' %>

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, local: true) do |form| %>

  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %>
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <h2><%= form.label :name %></h2>
    <%= form.text_field :name %>
  </p>
 
  <h2>Ingredients</h2>
  <%#= debug @recipe %>
  <%= react_component("IngredientList", {
      initialIngredients: @ingredients,
      editable: true,
      showAmount: true,
    }) %>

  <p>
    <h2><%= form.label :text %></h2>
    <%= form.text_area :text, :cols => 100, :rows => 10 %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/recipes/_table.html.erb
<% if @recipes.size > 0 %>
  <table class="recipes-table">
    <tr>
      <th>Name</th>
      <th>Published</th>
    </tr>
  
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.published_at.nil? ? 'Never' : recipe.published_at.to_date %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <em>No recipes found :(</em>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>
<%= render 'form' %>
<%= link_to 'Cancel', recipe_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<p> 
  <%= link_to 'Submit new recipe', new_recipe_path %>
</p>

<h2>Search recipes</h2>

<p>
  <%= react_component("RecipeSearch", {}) %>
</p>

<h2>All recipes</h2>
<%= render 'table' %>

app/views/recipes/new.html.erb
<h1>Submit a new recipe</h1>
<%= render 'form' %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<%= react_component("IngredientList", {
    initialIngredients: @ingredients,
    editable: false,
    showAmount: true,
  }) %>
 
<p>
  <strong>Text:</strong>
  <%= @recipe.text %>
</p>

<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
    </h2>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
    <% if @recipe.published_at.nil? %>
      <%= link_to 'Publish', publish_recipe_path(@recipe),
              method: :post,
              data: { confirm: 'Really publish recipe? It cannot be deleted after publishing.' } %>
      <%= link_to 'Destroy', recipe_path(@recipe),
              method: :delete,
              data: { confirm: 'Really delete recipe?' } %>
    <% else %>
      Published on <%= @recipe.published_at.to_date %>
    <% end %>
    <%= link_to 'Edit', edit_recipe_path(@recipe) %>
</p>

<%= link_to 'Back', recipes_path %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>
  <%= link_to 'Browse recipes', controller: 'recipes' %>
</p>
<p>
  <%= link_to 'Browse ingredients', controller: 'ingredients' %>
</p>